/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 16
#define LARGE_STATE_COUNT 7
#define SYMBOL_COUNT 17
#define ALIAS_COUNT 0
#define TOKEN_COUNT 10
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 4
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LF = 1,
  sym_comment = 2,
  sym_divider = 3,
  aux_sym_header_directive_token1 = 4,
  sym_directive_keyword = 5,
  sym_step_keyword = 6,
  sym_quoted_string = 7,
  sym_unquoted_arg = 8,
  sym_rest_of_line = 9,
  sym_source_file = 10,
  sym__line = 11,
  sym_header_directive = 12,
  sym_step = 13,
  sym_step_args = 14,
  aux_sym_source_file_repeat1 = 15,
  aux_sym_step_args_repeat1 = 16,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LF] = "\n",
  [sym_comment] = "comment",
  [sym_divider] = "divider",
  [aux_sym_header_directive_token1] = "header_directive_token1",
  [sym_directive_keyword] = "directive_keyword",
  [sym_step_keyword] = "step_keyword",
  [sym_quoted_string] = "quoted_string",
  [sym_unquoted_arg] = "unquoted_arg",
  [sym_rest_of_line] = "rest_of_line",
  [sym_source_file] = "source_file",
  [sym__line] = "_line",
  [sym_header_directive] = "header_directive",
  [sym_step] = "step",
  [sym_step_args] = "step_args",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_step_args_repeat1] = "step_args_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LF] = anon_sym_LF,
  [sym_comment] = sym_comment,
  [sym_divider] = sym_divider,
  [aux_sym_header_directive_token1] = aux_sym_header_directive_token1,
  [sym_directive_keyword] = sym_directive_keyword,
  [sym_step_keyword] = sym_step_keyword,
  [sym_quoted_string] = sym_quoted_string,
  [sym_unquoted_arg] = sym_unquoted_arg,
  [sym_rest_of_line] = sym_rest_of_line,
  [sym_source_file] = sym_source_file,
  [sym__line] = sym__line,
  [sym_header_directive] = sym_header_directive,
  [sym_step] = sym_step,
  [sym_step_args] = sym_step_args,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_step_args_repeat1] = aux_sym_step_args_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_divider] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_header_directive_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_directive_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_step_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_string] = {
    .visible = true,
    .named = true,
  },
  [sym_unquoted_arg] = {
    .visible = true,
    .named = true,
  },
  [sym_rest_of_line] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__line] = {
    .visible = false,
    .named = true,
  },
  [sym_header_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_step] = {
    .visible = true,
    .named = true,
  },
  [sym_step_args] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_step_args_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_args = 1,
  field_keyword = 2,
  field_value = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_args] = "args",
  [field_keyword] = "keyword",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_keyword, 0},
  [1] =
    {field_keyword, 0},
    {field_value, 2},
  [3] =
    {field_args, 2},
    {field_keyword, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(78);
      ADVANCE_MAP(
        '\n', 79,
        '"', 2,
        '#', 80,
        '-', 6,
        '\t', 82,
        ' ', 82,
        'C', 32,
        'c', 32,
        'D', 36,
        'd', 36,
        'E', 75,
        'e', 75,
        'F', 34,
        'f', 34,
        'G', 51,
        'g', 51,
        'L', 35,
        'l', 35,
        'S', 18,
        's', 18,
        'T', 10,
        't', 10,
        'U', 65,
        'u', 65,
        'V', 39,
        'v', 39,
        'W', 14,
        'w', 14,
      );
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(2);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(87);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(86);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '-') ADVANCE(4);
      END_STATE();
    case 4:
      if (lookahead == '-') ADVANCE(4);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(76);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(9);
      END_STATE();
    case 5:
      if (lookahead == '-') ADVANCE(81);
      END_STATE();
    case 6:
      if (lookahead == '-') ADVANCE(3);
      END_STATE();
    case 7:
      if (lookahead == '-') ADVANCE(5);
      END_STATE();
    case 8:
      if (lookahead == '-') ADVANCE(7);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(8);
      END_STATE();
    case 9:
      if (lookahead == '-') ADVANCE(7);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(8);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(9);
      END_STATE();
    case 10:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(31);
      END_STATE();
    case 11:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(61);
      END_STATE();
    case 12:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(15);
      END_STATE();
    case 13:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(58);
      END_STATE();
    case 14:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(38);
      END_STATE();
    case 15:
      if (lookahead == 'B' ||
          lookahead == 'b') ADVANCE(45);
      END_STATE();
    case 16:
      if (lookahead == 'B' ||
          lookahead == 'b') ADVANCE(50);
      END_STATE();
    case 17:
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(42);
      END_STATE();
    case 18:
      ADVANCE_MAP(
        'C', 52,
        'c', 52,
        'E', 47,
        'e', 47,
        'N', 13,
        'n', 13,
        'T', 11,
        't', 11,
        'U', 16,
        'u', 16,
      );
      END_STATE();
    case 19:
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(44);
      END_STATE();
    case 20:
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(69);
      END_STATE();
    case 21:
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(73);
      END_STATE();
    case 22:
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(83);
      END_STATE();
    case 23:
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(25);
      END_STATE();
    case 24:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(84);
      END_STATE();
    case 25:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(83);
      END_STATE();
    case 26:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(17);
      END_STATE();
    case 27:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(22);
      END_STATE();
    case 28:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(20);
      END_STATE();
    case 29:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(21);
      END_STATE();
    case 30:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(48);
      END_STATE();
    case 31:
      if (lookahead == 'G' ||
          lookahead == 'g') ADVANCE(63);
      END_STATE();
    case 32:
      if (lookahead == 'H' ||
          lookahead == 'h') ADVANCE(26);
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(37);
      END_STATE();
    case 33:
      if (lookahead == 'H' ||
          lookahead == 'h') ADVANCE(55);
      END_STATE();
    case 34:
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(46);
      END_STATE();
    case 35:
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(49);
      END_STATE();
    case 36:
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(66);
      END_STATE();
    case 37:
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(17);
      END_STATE();
    case 38:
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(71);
      END_STATE();
    case 39:
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(68);
      END_STATE();
    case 40:
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(70);
      END_STATE();
    case 41:
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(69);
      END_STATE();
    case 42:
      if (lookahead == 'K' ||
          lookahead == 'k') ADVANCE(84);
      END_STATE();
    case 43:
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(84);
      END_STATE();
    case 44:
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(74);
      END_STATE();
    case 45:
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(27);
      END_STATE();
    case 46:
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(43);
      END_STATE();
    case 47:
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(28);
      END_STATE();
    case 48:
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(29);
      END_STATE();
    case 49:
      if (lookahead == 'M' ||
          lookahead == 'm') ADVANCE(40);
      END_STATE();
    case 50:
      if (lookahead == 'M' ||
          lookahead == 'm') ADVANCE(41);
      END_STATE();
    case 51:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(72);
      END_STATE();
    case 52:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(57);
      END_STATE();
    case 53:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(84);
      END_STATE();
    case 54:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(60);
      END_STATE();
    case 55:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(69);
      END_STATE();
    case 56:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(59);
      END_STATE();
    case 57:
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(25);
      END_STATE();
    case 58:
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(64);
      END_STATE();
    case 59:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(84);
      END_STATE();
    case 60:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(67);
      END_STATE();
    case 61:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(70);
      END_STATE();
    case 62:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(43);
      END_STATE();
    case 63:
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(83);
      END_STATE();
    case 64:
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(33);
      END_STATE();
    case 65:
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(24);
      END_STATE();
    case 66:
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(12);
      END_STATE();
    case 67:
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(30);
      if (lookahead == 'U' ||
          lookahead == 'u') ADVANCE(62);
      END_STATE();
    case 68:
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(41);
      END_STATE();
    case 69:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(84);
      END_STATE();
    case 70:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(83);
      END_STATE();
    case 71:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(85);
      END_STATE();
    case 72:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(53);
      END_STATE();
    case 73:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(56);
      END_STATE();
    case 74:
      if (lookahead == 'U' ||
          lookahead == 'u') ADVANCE(23);
      END_STATE();
    case 75:
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(19);
      END_STATE();
    case 76:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(76);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(9);
      END_STATE();
    case 77:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(88);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(80);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_divider);
      if (lookahead == '-') ADVANCE(81);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(aux_sym_header_directive_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(82);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_directive_keyword);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_step_keyword);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_step_keyword);
      if (lookahead == 'F' ||
          lookahead == 'f') ADVANCE(54);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_quoted_string);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_unquoted_arg);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"') ADVANCE(87);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_rest_of_line);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(88);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 77},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [sym_divider] = ACTIONS(1),
    [aux_sym_header_directive_token1] = ACTIONS(1),
    [sym_directive_keyword] = ACTIONS(1),
    [sym_step_keyword] = ACTIONS(1),
    [sym_quoted_string] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(14),
    [sym__line] = STATE(2),
    [sym_header_directive] = STATE(2),
    [sym_step] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LF] = ACTIONS(5),
    [sym_comment] = ACTIONS(5),
    [sym_divider] = ACTIONS(5),
    [sym_directive_keyword] = ACTIONS(7),
    [sym_step_keyword] = ACTIONS(9),
    [sym_quoted_string] = ACTIONS(5),
  },
  [STATE(2)] = {
    [sym__line] = STATE(3),
    [sym_header_directive] = STATE(3),
    [sym_step] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(11),
    [anon_sym_LF] = ACTIONS(13),
    [sym_comment] = ACTIONS(13),
    [sym_divider] = ACTIONS(13),
    [sym_directive_keyword] = ACTIONS(7),
    [sym_step_keyword] = ACTIONS(9),
    [sym_quoted_string] = ACTIONS(13),
  },
  [STATE(3)] = {
    [sym__line] = STATE(3),
    [sym_header_directive] = STATE(3),
    [sym_step] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(15),
    [anon_sym_LF] = ACTIONS(17),
    [sym_comment] = ACTIONS(17),
    [sym_divider] = ACTIONS(17),
    [sym_directive_keyword] = ACTIONS(20),
    [sym_step_keyword] = ACTIONS(23),
    [sym_quoted_string] = ACTIONS(17),
  },
  [STATE(4)] = {
    [aux_sym_step_args_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(26),
    [anon_sym_LF] = ACTIONS(26),
    [sym_comment] = ACTIONS(26),
    [sym_divider] = ACTIONS(26),
    [aux_sym_header_directive_token1] = ACTIONS(28),
    [sym_directive_keyword] = ACTIONS(26),
    [sym_step_keyword] = ACTIONS(26),
    [sym_quoted_string] = ACTIONS(26),
  },
  [STATE(5)] = {
    [aux_sym_step_args_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(30),
    [anon_sym_LF] = ACTIONS(30),
    [sym_comment] = ACTIONS(30),
    [sym_divider] = ACTIONS(30),
    [aux_sym_header_directive_token1] = ACTIONS(28),
    [sym_directive_keyword] = ACTIONS(30),
    [sym_step_keyword] = ACTIONS(30),
    [sym_quoted_string] = ACTIONS(30),
  },
  [STATE(6)] = {
    [aux_sym_step_args_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(32),
    [anon_sym_LF] = ACTIONS(32),
    [sym_comment] = ACTIONS(32),
    [sym_divider] = ACTIONS(32),
    [aux_sym_header_directive_token1] = ACTIONS(34),
    [sym_directive_keyword] = ACTIONS(32),
    [sym_step_keyword] = ACTIONS(32),
    [sym_quoted_string] = ACTIONS(32),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(39), 1,
      aux_sym_header_directive_token1,
    ACTIONS(37), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      sym_comment,
      sym_divider,
      sym_directive_keyword,
      sym_step_keyword,
      sym_quoted_string,
  [13] = 2,
    ACTIONS(43), 1,
      aux_sym_header_directive_token1,
    ACTIONS(41), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      sym_comment,
      sym_divider,
      sym_directive_keyword,
      sym_step_keyword,
      sym_quoted_string,
  [26] = 1,
    ACTIONS(32), 8,
      ts_builtin_sym_end,
      anon_sym_LF,
      sym_comment,
      sym_divider,
      aux_sym_header_directive_token1,
      sym_directive_keyword,
      sym_step_keyword,
      sym_quoted_string,
  [37] = 1,
    ACTIONS(45), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      sym_comment,
      sym_divider,
      sym_directive_keyword,
      sym_step_keyword,
      sym_quoted_string,
  [47] = 1,
    ACTIONS(47), 7,
      ts_builtin_sym_end,
      anon_sym_LF,
      sym_comment,
      sym_divider,
      sym_directive_keyword,
      sym_step_keyword,
      sym_quoted_string,
  [57] = 2,
    STATE(11), 1,
      sym_step_args,
    ACTIONS(49), 2,
      sym_quoted_string,
      sym_unquoted_arg,
  [65] = 1,
    ACTIONS(51), 2,
      sym_quoted_string,
      sym_unquoted_arg,
  [70] = 1,
    ACTIONS(53), 1,
      ts_builtin_sym_end,
  [74] = 1,
    ACTIONS(55), 1,
      sym_rest_of_line,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(7)] = 0,
  [SMALL_STATE(8)] = 13,
  [SMALL_STATE(9)] = 26,
  [SMALL_STATE(10)] = 37,
  [SMALL_STATE(11)] = 47,
  [SMALL_STATE(12)] = 57,
  [SMALL_STATE(13)] = 65,
  [SMALL_STATE(14)] = 70,
  [SMALL_STATE(15)] = 74,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [17] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [20] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [26] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_step_args, 1, 0, 0),
  [28] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [30] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_step_args, 2, 0, 0),
  [32] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_step_args_repeat1, 2, 0, 0),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_step_args_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header_directive, 1, 0, 1),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_step, 1, 0, 1),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header_directive, 3, 0, 2),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_step, 3, 0, 3),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [53] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_flow_scenario(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
